### ISSUE TITLE
Search is too wel hidden

### ISSUE THREAD

**Issue by LucSmeets** [Sjoerdjanssenen/Subby-issues#10]
Adding a new service requires me to drag down in categories to search for a service. I didn't notice this until the 5th service. Might be nicer to have it visible at all times or have in animate up out of the way once you open the 'Add new service' categories page.

**Comment by LucSmeets** [comment]
reopen

**Comment by Sjoerdjanssenen** [comment]
An animation has been added the first two times you open a view.
