### ISSUE TITLE
iPhone 4 keyboard down issue

### ISSUE THREAD

**Issue by LucSmeets** [Sjoerdjanssenen/Subby-issues#14]

**Comment by LucSmeets** [comment]
Same issue als Laura " als je je wil registreren gaat het toetsenbord over confirm password heen en blijft daar staan terwijl je typt, is niet echt een bug meer een design ding i guess. either way niet erg handig om niks te zien"

**Comment by Sjoerdjanssenen** [comment]
Should be fixed.
