### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by LucSmeets** [Sjoerdjanssenen/Subby-issues#31]
1)
- Tried registering with my school mail adres
- Button didn't work OR
- Subby doesn't give me feedback on what went wrong

2)
- Annuleren becomes An...eren

![img_0031](https://cloud.githubusercontent.com/assets/16607591/13250472/7777774e-da2a-11e5-9f49-8dacf688c1e1.jpg)

**Comment by LucSmeets** [comment]
The passwords didn't match. Could register on my 2nd attempt.

**Comment by Sjoerdjanssenen** [comment]
Fixed.
