### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by LucSmeets** [Sjoerdjanssenen/Subby-issues#33]
In Nightmode, the 'Amount' is barely visible, even when it's really dark around me:
![img_0026](https://cloud.githubusercontent.com/assets/16607591/13251217/225e6f10-da2f-11e5-9dac-dbd1af88a190.jpg)
- Would be better if this was a couple of tints lighter.
- Option to make the service 'White' and make the amount the tint the service currently has.

'Add new service' the buttons to the right aren't tagging along with the Nightmode style:
![img_0033](https://cloud.githubusercontent.com/assets/16607591/13251277/7ac22b24-da2f-11e5-9079-2ae2775fcb05.jpg)

**Comment by Sjoerdjanssenen** [comment]
Fixed.

**Comment by LucSmeets** [comment]
Very sexy, chalkboard-style :facepunch:
