### ISSUE TITLE
'Logout'

### ISSUE THREAD

**Issue by LucSmeets** [Sjoerdjanssenen/Subby-issues#35]
Button placement is on the left, throughout the whole app, this is where the 'back' button is, which has me confused. Consider switching it to the right, or placing it at the bottom of the settings. I accidentally pressed it twice! 
Also, would be nice to have a 'are you sure?'

'Are you sure you want to log out?' (Yes | No )

-> 'Weet je zeker dat je wilt uitloggen? ( Ja | Nee )

**Comment by Sjoerdjanssenen** [comment]
The modal has been added. Moving it to the right, would mean moving 'done' to the left, which is contrary to where iOS places it.

**Comment by LucSmeets** [comment]
'Nee.' -> 'Nee, niet echt!' 
'No.' -> 'No, not really!'

Then considered fixed :dancers:

**Comment by Sjoerdjanssenen** [comment]
Added.
